package constants;

import utils.UserJsonReader;

public class GlobalData {

    public static final String TRUE = "True";
    public static final String FALSE = "False";
    public static final String WELCOME_TITLE = "Welcome";
    public static final String LOGIN_TITLE = "Login";
    public static final String EUR = "EUR";
    public static final String USD = "USD";
    public static final String RUB = "RUB";
    public static final String CONFIRMATION_CODE_TITLE = "OrderConfirmationScreen code";
    public static final String CONFIRMATION_CODE_OPTIONS_TITLE = "OrderConfirmationScreen code options";
    public static final String PROMO_TITLE = "Promo";
    public static final String MAIN_TITLE = "Main";
    public static final String FILTER_TITLE = "Filter";
    public static final String PRODUCTS_TITLE = "Products";
    public static final String PAYMENTS_TITLE = "Payments";
    public static final String PAYMENT_BY_BANK_DETAILS_TITLE = "Payments by bank details";
    public static final String AUTO_PAYMENTS_TITLE = "Auto payments";
    public static final String ADDITION_AUTO_PAYMENT_TITLE = "Addition auto payment";
    public static final String NEW_AUTOPAY_TITLE = "New autopay";
    public static final String AUTOPAY_DETAILS_TITLE = "Autopay details";
    public static final String PAYMENT_BY_BANK_DETAILS_ENTER_AMOUNT_TITLE = "Payments by bank details: enter account and amount";
    public static final String MORE_TITLE = "More";
    public static final String CURRENCY_EXCHANGE_TITLE = "Currency exchange";
    public static final String BANK_BRANCHES_TITLE = "Bank branches";
    public static final String CONTACTS_TITLE = "Contacts";
    public static final String OPEN_ACCOUNTS_TITLE = "Open accounts";
    public static final String OPEN_ACCOUNT_CREATING_TITLE = "Open account creating";
    public static final String OPEN_DEPOSIT_TITLE = "Open deposit";
    public static final String OPEN_CREDIT_TITLE = "Open credit";
    public static final String DEPOSITS_TITLE = "Deposits";
    public static final String EMPTY_DEPOSITS_PAGE_TEXT = "You dont't have any open deposits or saving accounts yet.";
    public static final String DEPOSIT_DETAILS_TITLE = "Deposit details";
    public static final String CARDS_TITLE = "Cards";
    public static final String CARD_DETAILS_TITLE = "Card details";
    public static final String CARD_MANAGE_TITLE = "Card manage";
    public static final String BLOCK_CARD_CONFIRMATION_TITLE = "Block card confirmation";
    public static final String OPEN_CARD_TITLE = "Open card";
    public static final String SELECTION_TITLE = "Selection";
    public static final String DEPOSIT_DESCRIPTION_TITLE = "Deposit Description";
    public static final String SELECT_ACCOUNT_TITLE = "Select Account";
    public static final String SELECTION_RESULTS_TITLE = "Selection results";
    public static final String USER_PROFILE_TITLE = "User profile";
    public static final String USER_NOTIFICATIONS_TITLE = "User notifications";
    public static final String SET_NEW_EMAIL_TITLE = "Set a new email";
    public static final String EMAIL_SUCCESS_CHANGED_TITLE = "Email has been successfully changed";
    public static final String PERSONAL_CABINET_TITLE = "Personal cabinet";
    public static final String CHANGE_PROFILE_PHOTO_ALERT= "Change Profile Photo Alert ";
    public static final String DELETE_ACCOUNT_ALERT= "Delete Account Alert ";
    public static final String REGISTRATION_ADDRESS_TITLE = "Registration address";
    public static final String PASSPORT_DETAILS_TITLE = "Passport details page";
    public static final int LENGTH_ACCOUNT_NUMBER = 34;
    public static final String USER_PROFILE_SAFETY_TITLE = "User profile safety";
    public static final String SET_APPLICATION_PASSWORD_TITLE = " Set application password";
    public static final String ENTER_APPLICATION_PASSWORD_TITLE = " ENTER application password";
    public static final String VALID_USER_DATA_FILE_SOURCE = "src/test/resources/test_data.json";
    public static final String VALID_LOGIN_USER = UserJsonReader
            .getValueByKey(VALID_USER_DATA_FILE_SOURCE, "validLoginUser");
    public static final String VALID_PASSWORD_USER = UserJsonReader
            .getValueByKey(VALID_USER_DATA_FILE_SOURCE, "validPasswordUser");
    public static final String VALID_LOGIN_ADMIN = UserJsonReader
            .getValueByKey(VALID_USER_DATA_FILE_SOURCE, "validLoginAdmin");
    public static final String VALID_PASSWORD_ADMIN = UserJsonReader
            .getValueByKey(VALID_USER_DATA_FILE_SOURCE, "validPasswordAdmin");
    public static final String NEW_EMAIL = UserJsonReader
            .getValueByKey(VALID_USER_DATA_FILE_SOURCE, "newEmail");
    public static final String OLD_EMAIL = UserJsonReader
            .getValueByKey(VALID_USER_DATA_FILE_SOURCE, "oldEmail");
    public static final String VALID_PHONE_NUMBER = "78965432170";
    public static final String OPEN_CHOOSE_CREDIT_TITLE = "Open choose credit title";
    public static final String OPEN_INLAY_INFORMATION_TITLE = "Open inlay information title";
    public static final String OPEN_HOME_SETTINGS_TITLE = "Open home settings title";
    public static final String CLOSE_CARD_SUCCESS_TITLE = "Close card information title";
    public static final String NOT_VALID_LOGIN = "1112523523424234243";
    public static final String NOT_VALID_PASSWORD = "NOTVALID123";
    public static final String BASE_URL = "http://0.0.0.0:4723/wd/hub";
    public static final String PASSWORD_EXAMPLE = "pA55w0RD1234567890123wqrws33fvxcf";
    public static final String LOGIN_EXAMPLE = "111ln0123456789012345afsaET5412We";
    public static final String CODE_EXAMPLE = "123456789012345678901234567890123";
    public static final String WRONG_CODE_FIVE_TIMES = "You entered the wrong code 5 times";
    public static final String CODE_EXPIRATION_10_SECONDS = "Code expiration 04:50";
    public static final String CODE_HAS_EXPIRED = "Code has expired";
    public static final String CODE_EXPIRATION_START = "Code expiration 04:59";
    public static final String CHANGE_PASSWORD_TITLE = "Change password";
    public static final String VALID_CARD_NUMBER = "4220 0000 0001 7224";
    public static final String VALID_ACCOUNT_NUMBER = "1002679482602702252743178286019286";
    public static final String VALID_TO_ACCOUNT_NUMBER= "1002262543692863891663712409753913";
    public static final String AMOUNT_200 = "200.00";
    public static final String AMOUNT_100 = "100.00";
    public static final String AMOUNT_100_WITH_ONE_NULL = "100.0";
    public static final String AMOUNT_1 = "1.00";
    public static final String AMOUNT_0 = "0";
    public static final String TRANSFER_ASSIGNMENT_MESSAGE = "Message";
    public static final String TRANSFERS_TITLE = "Transfers";
    public static final String TRANSFERS_TO_CONNECTED_CARD_TITLE = "Transfers to connected card";
    public static final String TRANSFER_BY_CARD_NUMBER_TITLE = "Transfer by card number";
    public static final String TRANSFER_BY_PHONE_NUMBER_TITLE = "Transfer by phone number";
    public static final String TRANSFER_BY_ACCOUNT_NUMBER_TITLE = "Transfer by account number";
    public static final String DETAILS_FOR_TRANSFER_BY_PHONE_NUMBER_TITLE = "Details for transfer by phone number";
    public static final String CONFIRMATION_TRANSFER_TITLE = "Confirmation transfer screen";
    public static final String CONFIRMATION_BY_PHONE_TRANSFER_TITLE = "Confirmation transfer by phone number screen";
    public static final String CONFIRMATION_BY_ACCOUNT_TRANSFER_TITLE = "Confirmation transfer by account number screen";
    public static final String CONFIRMATION_PAYMENT_BY_BANK_DETAILS_TITLE = "Confirmation payment by bank details screen";
    public static final String AMOUNT_TITLE = "Amount screen";
    public static final String FIRST_CARD_NUMBER_USER_1110010 = "************0027";
    public static final String SECOND_CARD_NUMBER_USER_1110010 = "************0035";
    public static final String EMPTY_FIELD = "";
    public static final String RESULT_TITLE = "Result screen";
    public static final String ENTER_RECIPIENTS_CARD_NUMBER = "Enter recipient`s card number";
    public static final String THIS_PAYMENT_SYSTEM_IS_UNAVAILABLE_FOR_TRANSFERS =
            "This payment system is unavailable for transfers";
    public static final String YOU_ENTERED_THE_WRONG_CODE_5_TIMES = "You entered the wrong code 5 times";
    public static final String INVALID_ID_FOR_DEPOSIT_PRODUCT_GET = "e5005d30-8469-40-5-b391-a282666baae7";
    public static final String VALID_ID_FOR_EXISTENT_DEPOSIT_PRODUCT = "c75ec5bb-be49-48e3-8b6e-ee57640b46ca";
    public static final String VALID_NAME_FOR_EXISTENT_DEPOSIT_PRODUCT = "TEST AQA Deposit";
    public static final String VALID_CURRENCY_NAME_FOR_EXISTENT_DEPOSIT_PRODUCT = "EUR";
    public static final String VALID_ID_FOR_NON_EXISTENT_DEPOSIT_PRODUCT = "7b279c58-7263-466b-82b6-e3d8f002620a";
    public static final String VALID_ID_FOR_EXISTENT_DEPOSIT = "7dcc1250-7897-4a2f-8c0c-c4bdfc7988ec";
    public static final String VALID_ID_FOR_NON_EXISTENT_DEPOSIT = "7dcc1250-7897-4a2f-8c0c-c4bdfc7900ec";
    public static final String ACCOUNT_CREATED = "Account created";
    public static final String NEW_ACCOUNT = "New account";
    public static final String COMMON_PAGE = "Common page";
    public static final String BLOCK_CARD_ALERT_TITLE = "Block the card";
    public static final String CLOSE_CARD_ALERT_TITLE = "Close card";
    public static final String PAYMENT_BY_BANK_DETAILS_ERROR_ALERT_TITLE = "Error";
    public static final String PAYMENT_BY_BANK_DETAILS_ERROR_ALERT_MESSAGE = "Unfortunately, this bank is not found.Try again";
    public static final String BLOCK_CARD_ALERT_MESSAGE = "Are you sure you want to block this card?";
    public static final String CLOSE_CARD_ALERT_MESSAGE = "Are you sure you want to close the card?\n" +
            "The card won’t be usable.";
    public static final String CLOSE_CARD_SUCCESS_MESSAGE ="The card has been successfully closed";
    public static final String BLOCK_CARD_CONFIRMATION_ALERT_TITLE = "Card blocked";
    public static final String BLOCK_CARD_CONFIRMATION_ALERT_MESSAGE = "Inform the bank staff about suspicious activity or loss of the card";
    public static final String CARD_STATUS_ACTIVE = "ACTIVE";
    public static final String CARD_STATUS_BLOCKED = "BLOCKED";
    public static final String VALID_USER_SOURCE_CARD = "e2bec918-dbf1-4705-8abd-c1beda2a2cbc";
    public static final String VALID_ADMIN_SOURCE_CARD = "d70a5239-5495-43a5-9320-732314f2d20d";
    //public static final String VALID_RECIPIENT_CARD = "8183131f-d4e6-4be6-b7c7-b72a07ae33d9";
    public static final String FREQUENCY = "0Y_0M_0W_0D";
    public static final String DEMO_TITLE = "Demo";
    public static final String DEMO_USER_PROFILE_TITLE = "Demo user profile";
    public static final String PENALTY_ID = "e0bfc3db-f94d-4cbc-ae42-c926b8e62518";
    public static final String BANK_NAME = "BankName";
    public static final String VALID_CARD_PRODUCT_ID_FOR_USER = "c8f8e21b-0b4d-42fb-8926-e22e61080907";
    public static final String VALID_ID_FOR_PAYMENT_SERVICE = "ab9251f2-1746-45bc-a33b-39a206c9f2e3";
    public static final String VALID_CREDIT_CARD_TYPE = "08e2edd0-b0e1-4ca5-83ae-a3ea9149d3e5";
    public static final String VALID_CREDIT_ACCOUNT_ID_WITH_CURRENCY_USD_FOR_ADMIN = "10101c82-d170-438c-9037-19060a3acc52";
    public static final String VALID_CREDIT_ACCOUNT_ID_WITH_CURRENCY_USD_FOR_USER = "90e853d4-0816-4901-bc97-d47d4b65ecbd";
    public static final String VALID_CREDIT_EMPLOYER_IDENTIFICATION_ID = "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11";
    public static String COUNT = "count";
    public static final String VALID_CREDIT_PENALTY_ID = "74795033-d222-4919-b249-024a18335d23";
}
